language: php

os:
  - linux

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - hhvm
  - nightly

matrix:
  allow_failures:
    - php: hhvm
    - php: nightly
  include:
    - php: 7.1
      env: PHP_STAN=1

install:
  - composer self-update
  - composer install

script:
  - bin/codecept run
  - if [ "$PHPSTAN" = "1" ]; then vendor/bin/phpstan analyse src --level=7 --ansi --no-progress -c phpstan.neon; fi