language: php

os:
  - linux

php:
  - 5.6
  - 7.0
  - 7.1
  - hhvm
  - nightly

matrix:
  allow_failures:
    - php: hhvm
    - php: nightly

install:
    - composer self-update
    - composer install

script: bin/codecept run